plugins { id 'com.android.application' }

android {
    namespace 'jp.ryu.silentpipcamera'
    compileSdk 35

    defaultConfig {
        applicationId 'jp.ryu.anatomydiffusion'
        minSdk 29
        targetSdk 35
        versionCode 3
        versionName '0.2.1'
    }
}

dependencies {
    implementation 'com.google.mediapipe:tasks-vision-image-generator:0.10.26.1'
}
